# -*- coding: utf-8 -*-
"""ai2_mcts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1scdXqV9wwhpMmN6l3jApd4SAlnNs_0NF
"""

from game import Board
from typing import Optional, Tuple
import math
import time
import random
import copy

# ---------------------------------------------------------------------------
# MCTS CONSTANTS
# ---------------------------------------------------------------------------
C_PUCT      = 1.414   # UCB exploration constant  (sqrt(2) is standard)
MAX_ROLLOUT = 30      # max moves per simulation before declaring draw
CANDIDATE_RADIUS = 2  # same candidate pruning as minimax agent
MAX_CANDIDATES   = 15


# ===========================================================================
# PART 1 — CANDIDATE MOVES  (reuse same logic as minimax agent)
# ===========================================================================

def get_candidate_moves(board: Board) -> list:
    """
    Return empty cells within CANDIDATE_RADIUS of any occupied cell.
    If the board is empty, return the center cell only.

    INPUT:  board
    OUTPUT: list of (r, c) tuples
    """
    occupied = list(zip(*board.grid.nonzero()))
    if not occupied:
        center = board.size // 2
        return [(center, center)]

    candidates = set()
    for (r, c) in occupied:
        for dr in range(-CANDIDATE_RADIUS, CANDIDATE_RADIUS + 1):
            for dc in range(-CANDIDATE_RADIUS, CANDIDATE_RADIUS + 1):
                nr, nc = r + dr, c + dc
                if (0 <= nr < board.size and
                        0 <= nc < board.size and
                        board.grid[nr, nc] == 0):
                    candidates.add((nr, nc))

    return list(candidates)


# ===========================================================================
# PART 2 — NODE
# ===========================================================================

class MCTSNode:
    """
    A single node in the MCTS tree.

    Attributes
    ----------
    board       : current board state at this node
    player      : the player whose turn it is TO MOVE from this node
    parent      : parent MCTSNode, or None if root
    move        : the (r, c) move that led FROM parent TO this node
    children    : list of MCTSNode - expanded children
    visits      : N(s) - how many times this node was visited
    wins        : W(s) - total win score accumulated via backprop
                  (wins are always from the perspective of the player
                   who MADE the move that created this node, i.e. parent.player)
    untried_moves : moves not yet expanded (initially all candidates)
    """

    def __init__(self, board: Board, player: int,
                 parent: Optional["MCTSNode"] = None,
                 move: Optional[Tuple[int, int]] = None):
        self.board         = board
        self.player        = player
        self.parent        = parent
        self.move          = move
        self.children      : list["MCTSNode"] = []
        self.visits        : int   = 0
        self.wins          : float = 0.0
        self.untried_moves : list  = get_candidate_moves(board)[:MAX_CANDIDATES]

    def is_fully_expanded(self) -> bool:
        """Return True when every candidate move has been expanded."""
        return len(self.untried_moves) == 0

    def is_terminal(self) -> bool:
        """
        Return True if this node represents a finished game state.
        A node is terminal if:
            - the move that created it was a winning move, OR
            - the board is full (draw)

        HINT: use board.check_win(r, c, last_player) where last_player
              is the opponent of self.player (they just moved).
              Be careful: if self.move is None (root), it's never terminal.

        INPUT:  self
        OUTPUT: bool
        """
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE
        # ---------------------------------------------------------------------------
        if self.move is None:
            return False
        if self.board.check_win(self.move[0], self.move[1], 3 - self.player) or self.board.is_full():
            return True
        return False


    def ucb_score(self, c: float = C_PUCT) -> float:
        """
        UCB1 score for this node (used by parent to select which child to visit).

            UCB1 = (wins / visits) + c * sqrt(ln(parent.visits) / visits)

        Return +inf if visits == 0 (unvisited node always gets priority).

        INPUT:  self, c — exploration constant
        OUTPUT: float
        """
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE
        # ---------------------------------------------------------------------------
        visits = self.visits
        wins = self.wins
        if visits == 0:
            return math.inf
        return (wins / visits) + c * math.sqrt(math.log(self.parent.visits) / visits)

    def best_child(self, c: float = C_PUCT) -> "MCTSNode":
        """
        Return the child with the highest UCB score.

        INPUT:  self, c
        OUTPUT: MCTSNode
        """
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (~1 line)
        # ---------------------------------------------------------------------------
        return max(self.children, key=lambda child: child.ucb_score(c))

    def expand(self) -> "MCTSNode":
        """
        Pop one move from untried_moves, create a child node for it, and
        append it to self.children.

        Steps:
            1. Pop a random move from self.untried_moves.
            2. Copy self.board and apply the move for self.player.
            3. Create a new MCTSNode with:
                   board  = new board copy
                   player = opponent (3 - self.player)
                   parent = self
                   move   = the popped move
            4. Append to self.children and return the new node.

        INPUT:  self
        OUTPUT: MCTSNode — the newly created child
        """
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (~6 lines)
        # ---------------------------------------------------------------------------
        move = self.untried_moves.pop()
        move = (int(move[0]), int(move[1]))
        new_board = self.board.copy()
        new_board.make_move(move[0], move[1], self.player)
        child = MCTSNode(new_board, 3 - self.player, self, move)
        self.children.append(child)
        return child

    def backpropagate(self, result: float) -> None:
        """
        Walk from this node to the root, updating visits and wins.

        `result` is from the perspective of the player who MADE the move
        leading to this node (i.e. self.parent.player if parent exists).

            self.visits += 1
            self.wins   += result
            if self.parent:
                self.parent.backpropagate(1 - result)   # flip perspective

        The flip `1 - result` works because result ∈ {0, 0.5, 1}:
            win for mover  → 1    → parent sees 0   (bad for them)
            draw           → 0.5  → parent sees 0.5 (neutral)
            loss for mover → 0    → parent sees 1   (good for them)

        INPUT:  self, result — float ∈ {0, 0.5, 1}
        OUTPUT: None  (mutates nodes in place)
        """
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (~4 lines)
        # ---------------------------------------------------------------------------
        self.visits += 1
        self.wins += result
        if self.parent:
            self.parent.backpropagate(1 - result)



# ===========================================================================
# PART 3 — ROLLOUT  (random simulation from a given state)
# ===========================================================================

def rollout(board: Board, player: int) -> float:
    """
    Simulate a random game from the given board state and return the result
    from `player`'s perspective.

    Algorithm:
        current_player = player
        for up to MAX_ROLLOUT steps:
            candidates = get_candidate_moves(board)
            if no candidates: return 0.5  (draw)

            HINT: add a simple heuristic — before picking randomly,
                  check if any candidate is an immediate win for current_player
                  or an immediate block (opponent about to win).
                  If found, play that move instead of random.
                  This significantly improves rollout quality without a network.

            pick a move (random or heuristic), apply it
            if current_player wins: return 1.0 if current_player == player else 0.0
            flip current_player

        return 0.5  (draw / horizon)

    INPUT:
        board   — Board (will be MUTATED then restored; make a copy before calling)
        player  — the perspective player (1 or 2)
    OUTPUT:
        float — 1.0 (player wins), 0.0 (player loses), 0.5 (draw)

    NOTE: caller is responsible for passing a COPY of the board.
    """
    # ---------------------------------------------------------------------------
    # YOUR CODE HERE
    # ---------------------------------------------------------------------------
    current_player = player
    for _ in range(MAX_ROLLOUT):
        candidates = get_candidate_moves(board)
        if not candidates:
            return 0.5

        # Check immediate win for current_player
        move = None
        for candidate in candidates:
            board.make_move(candidate[0], candidate[1], current_player)
            if board.check_win(candidate[0], candidate[1], current_player):
                board.undo_move(candidate[0], candidate[1])
                move = candidate
                break
            board.undo_move(candidate[0], candidate[1])

        # Check immediate block (opponent about to win)
        if move is None:
            opponent = 3 - current_player
            for candidate in candidates:
                board.make_move(candidate[0], candidate[1], opponent)
                if board.check_win(candidate[0], candidate[1], opponent):
                    board.undo_move(candidate[0], candidate[1])
                    move = candidate
                    break
                board.undo_move(candidate[0], candidate[1])

        # Otherwise random
        if move is None:
            move = random.choice(candidates)

        board.make_move(move[0], move[1], current_player)
        if board.check_win(move[0], move[1], current_player):
            return 1.0 if current_player == player else 0.0
        current_player = 3 - current_player

    return 0.5


# ===========================================================================
# PART 4 — MCTS MAIN LOOP
# ===========================================================================

def mcts_search(board: Board, player: int,
                time_limit: float = 15.0) -> Tuple[int, int]:
    """
    Run MCTS from the given board state and return the best move.

    Algorithm (standard 4-phase loop):
        root = MCTSNode(board_copy, player)

        while time not exceeded:
            # 1. SELECTION
            #    Start at root. While node is fully expanded and not terminal,
            #    descend via best_child(C_PUCT).

            # 2. EXPANSION
            #    If node is not terminal and not fully expanded,
            #    call node.expand() to get a new child node.

            # 3. SIMULATION
            #    Run rollout() from a COPY of the expanded node's board,
            #    with the expanded node's player to move.

            # 4. BACKPROPAGATION
            #    Call node.backpropagate(result).
            #    result is from the perspective of the player who just moved
            #    INTO the expanded node (i.e. expanded_node.parent.player).

        # SELECT BEST MOVE
        # Return the move of the child of root with the MOST visits
        # (not highest win rate — visit count is more robust).

    INPUT:
        board      : Board
        player     : 1 or 2
        time_limit : wall-clock budget in seconds
    OUTPUT:
        Tuple[int, int] — best (r, c) move

    HINT: print iteration count and best move stats at the end for debugging.
    """
    root = MCTSNode(board.copy(), player)
    start = time.time()
    iterations = 0

    # Pre-check: immediate win or block before MCTS
    candidates = get_candidate_moves(board)
    for move in candidates:
        board.make_move(move[0], move[1], player)
        if board.check_win(move[0], move[1], player):
            board.undo_move(move[0], move[1])
            return move
        board.undo_move(move[0], move[1])

    opponent = 3 - player
    for move in candidates:
        board.make_move(move[0], move[1], opponent)
        if board.check_win(move[0], move[1], opponent):
            board.undo_move(move[0], move[1])
            return move
        board.undo_move(move[0], move[1])

    while time.time() - start < time_limit:
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (~20 lines)
        # ---------------------------------------------------------------------------
        node = root
        while node.is_fully_expanded() and not node.is_terminal():
            node = node.best_child()

        if not node.is_terminal():
            node = node.expand()
            result = rollout(node.board.copy(), node.player)
            node.backpropagate(result)
        else:
            result = 0.5
            node.backpropagate(result)
        iterations += 1

    # ---------------------------------------------------------------------------
    # YOUR CODE HERE — select and return best move  (~3 lines)
    # ---------------------------------------------------------------------------
    best_child = root.children[0]
    for child in root.children:
        if child.visits > best_child.visits:
            best_child = child
    print(f"MCTS iterations: {iterations}")
    print(f"Best move: {best_child.move}")
    return best_child.move


# ===========================================================================
# TESTS
# ===========================================================================
# if __name__ == "__main__":
#     board = Board(15)

#     # ------------------------------------------------------------------
#     # 1. MCTSNode init
#     # ------------------------------------------------------------------
#     node = MCTSNode(copy.deepcopy(board), player=1)
#     assert node.visits == 0
#     assert node.wins   == 0.0
#     assert node.parent is None
#     assert node.move   is None
#     assert len(node.untried_moves) == 1  # empty board → center only
#     print("PASS: MCTSNode init")

#     # ------------------------------------------------------------------
#     # 2. is_terminal — root is never terminal
#     # ------------------------------------------------------------------
#     assert not node.is_terminal(), "root (no move made) must not be terminal"
#     print("PASS: is_terminal root")

#     # ------------------------------------------------------------------
#     # 3. expand — creates a child correctly
#     # ------------------------------------------------------------------
#     child = node.expand()
#     assert child.parent is node
#     assert child.move is not None
#     assert child.player == 2          # opponent's turn after player 1 moves
#     assert len(node.children) == 1
#     assert len(node.untried_moves) == 0   # only 1 candidate (center), now used
#     print("PASS: expand")

#     # ------------------------------------------------------------------
#     # 4. backpropagate
#     # ------------------------------------------------------------------
#     child.backpropagate(1.0)          # child's mover (player 1) wins
#     assert child.visits == 1
#     assert child.wins   == 1.0
#     assert node.visits  == 1
#     assert node.wins    == 0.0        # parent sees 1 - 1.0 = 0.0
#     print("PASS: backpropagate")

#     # ------------------------------------------------------------------
#     # 5. ucb_score — unvisited node returns inf
#     # ------------------------------------------------------------------
#     board2 = Board(15)
#     board2.make_move(7, 7, 1)
#     root2 = MCTSNode(copy.deepcopy(board2), player=2)
#     c1 = root2.expand()
#     assert c1.ucb_score() == math.inf, "unvisited child must return inf"
#     print("PASS: ucb_score unvisited")

#     # ------------------------------------------------------------------
#     # 6. rollout — returns valid result
#     # ------------------------------------------------------------------
#     board3 = Board(15)
#     board3.make_move(7, 7, 1)
#     result = rollout(copy.deepcopy(board3), player=1)
#     assert result in (0.0, 0.5, 1.0), f"rollout must return 0, 0.5 or 1, got {result}"
#     print("PASS: rollout valid result")

#     # ------------------------------------------------------------------
#     # 7. mcts_search — take winning move immediately
#     # ------------------------------------------------------------------
#     board4 = Board(15)
#     for col in range(4):
#         board4.make_move(0, col, 1)
#     move = mcts_search(board4, player=1, time_limit=15.0)
#     assert move == (0, 4), f"MCTS should complete 5-in-row, got {move}"
#     print("PASS: mcts_search takes win")

#     # ------------------------------------------------------------------
#     # 8. mcts_search — block opponent's open 4
#     # ------------------------------------------------------------------
#     board5 = Board(15)
#     for col in range(4):
#         board5.make_move(0, col, 2)
#     move = mcts_search(board5, player=1, time_limit=15.0)
#     assert move[0] == 0 and move[1] in (4,), \
#         f"MCTS should block row 0, got {move}"
#     print("PASS: mcts_search blocks opponent 4")

#     # ------------------------------------------------------------------
#     # 9. mcts_search — returns within time limit
#     # ------------------------------------------------------------------
#     board6 = Board(15)
#     random.seed(42)
#     for _ in range(10):
#         r, c = random.randint(5, 9), random.randint(5, 9)
#         if board6.grid[r, c] == 0:
#             board6.make_move(r, c, random.choice([1, 2]))
#     t0      = time.time()
#     move    = mcts_search(board6, player=1, time_limit=15.0)
#     elapsed = time.time() - t0
#     assert move is not None,     "must always return a move"
#     assert elapsed <= 16.0,       f"exceeded time limit: {elapsed:.1f}s"
#     print(f"PASS: mcts_search returned in {elapsed:.2f}s")

#     print("\n=== All tests passed! ===")