# -*- coding: utf-8 -*-
"""ai3_minimax_anytimesearch_mcts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hH9-zVpoIvaLcGphFaboWA1455Uhgip-
"""

from game import Board
from typing import Optional, Tuple
import math
import time
import random

# ---------------------------------------------------------------------------
# HYBRID CONSTANTS
# ---------------------------------------------------------------------------
C_PUCT           = 1.414   # UCB exploration constant
TOP_K            = 3       # number of MCTS candidates handed to minimax
CANDIDATE_RADIUS = 2
MAX_CANDIDATES   = 15
MAX_ROLLOUT      = 30      # max moves per simulation before declaring draw

# Scoring constants (same as minimax agent)
SCORES = {1: 10, 2: 100, 3: 1_000, 4: 10_000, 5: 1_000_000}
WIN_SCORE  =  SCORES[5]
LOSE_SCORE = -SCORES[5]

DIRECTIONS = [
    (0, 1),   # horizontal
    (1, 0),   # vertical
    (1, 1),   # diagonal
    (1, -1),  # anti-diagonal
]


# ===========================================================================
# PART 1 — CANDIDATE MOVES  (same as minimax and MCTS agents)
# ===========================================================================

def get_candidate_moves(board: Board) -> list:
    """
    Return empty cells within CANDIDATE_RADIUS of any occupied cell.
    If the board is empty, return the center cell only.
    """
    occupied = list(zip(*board.grid.nonzero()))
    if not occupied:
        center = board.size // 2
        return [(center, center)]

    candidates = set()
    for (r, c) in occupied:
        for dr in range(-CANDIDATE_RADIUS, CANDIDATE_RADIUS + 1):
            for dc in range(-CANDIDATE_RADIUS, CANDIDATE_RADIUS + 1):
                nr, nc = r + dr, c + dc
                if (0 <= nr < board.size and
                        0 <= nc < board.size and
                        board.grid[nr, nc] == 0):
                    candidates.add((nr, nc))

    return list(candidates)


# ===========================================================================
# PART 2 — HEURISTIC EVALUATION  (same as minimax agent)
# ===========================================================================

def score_window(p_cnt: int, o_cnt: int) -> int:
    """Score a single 5-cell window for ONE player."""
    if p_cnt > 0 and o_cnt == 0:
        return SCORES[p_cnt]
    return 0


def evaluate(board: Board, player: int) -> int:
    """
    Heuristic evaluation of the full board for `player`.
    Scans all 5-cell windows in all 4 directions.

    INPUT:  board, player
    OUTPUT: int — positive = good for player, negative = bad
    """
    opponent = 3 - player
    score    = 0

    for (dr, dc) in DIRECTIONS:
        for r in range(board.size):
            for c in range(board.size):
                er, ec = r + 4 * dr, c + 4 * dc
                if not (0 <= er < board.size and 0 <= ec < board.size):
                    continue

                p_cnt = 0
                o_cnt = 0
                for i in range(5):
                    cell = board.grid[r + i * dr, c + i * dc]
                    if cell == player:
                        p_cnt += 1
                    elif cell == opponent:
                        o_cnt += 1

                score += score_window(p_cnt, o_cnt)
                score -= score_window(o_cnt, p_cnt)

    return score


# ===========================================================================
# PART 3 — MCTS NODE  (same as MCTS agent, with heuristic rollout)
# ===========================================================================

def _rollout(board: Board, player: int) -> float:
    """
    Heuristic rollout — same implementation as mcts.py rollout().
    Returns float ∈ {0.0, 0.5, 1.0} from `player`'s perspective.

    HINT: copy your rollout() implementation from mcts.py here.

    INPUT:  board (copy — will be mutated), player
    OUTPUT: float
    """
    # ---------------------------------------------------------------------------
    # YOUR CODE HERE  (copy from mcts.py)
    # ---------------------------------------------------------------------------
    current_player = player
    for _ in range(MAX_ROLLOUT):
        candidates = get_candidate_moves(board)
        if not candidates:
            return 0.5

        # Check immediate win for current_player
        move = None
        for candidate in candidates:
            board.make_move(candidate[0], candidate[1], current_player)
            if board.check_win(candidate[0], candidate[1], current_player):
                board.undo_move(candidate[0], candidate[1])
                move = candidate
                break
            board.undo_move(candidate[0], candidate[1])

        # Check immediate block (opponent about to win)
        if move is None:
            opponent = 3 - current_player
            for candidate in candidates:
                board.make_move(candidate[0], candidate[1], opponent)
                if board.check_win(candidate[0], candidate[1], opponent):
                    board.undo_move(candidate[0], candidate[1])
                    move = candidate
                    break
                board.undo_move(candidate[0], candidate[1])

        # Otherwise random
        if move is None:
            move = random.choice(candidates)

        board.make_move(move[0], move[1], current_player)
        if board.check_win(move[0], move[1], current_player):
            return 1.0 if current_player == player else 0.0
        current_player = 3 - current_player

    return 0.5


class MCTSNode:
    """
    MCTS tree node — identical to mcts.py MCTSNode.
    Used in Phase 1 (MCTS exploration).
    """

    def __init__(self, board: Board, player: int,
                 parent: Optional["MCTSNode"] = None,
                 move: Optional[Tuple[int, int]] = None):
        self.board         = board
        self.player        = player
        self.parent        = parent
        self.move          = move
        self.children      : list["MCTSNode"] = []
        self.visits        : int   = 0
        self.wins          : float = 0.0
        self.untried_moves : list  = get_candidate_moves(board)[:MAX_CANDIDATES]

    def is_fully_expanded(self) -> bool:
        return len(self.untried_moves) == 0

    def is_terminal(self) -> bool:
        """Same as mcts.py MCTSNode.is_terminal()."""
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (copy from mcts.py)
        # ---------------------------------------------------------------------------
        if self.move is None:
            return False
        if self.board.check_win(self.move[0], self.move[1], 3 - self.player) or self.board.is_full():
            return True
        return False

    def ucb_score(self, c: float = C_PUCT) -> float:
        """Same as mcts.py MCTSNode.ucb_score()."""
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (copy from mcts.py)
        # ---------------------------------------------------------------------------
        visits = self.visits
        wins = self.wins
        if visits == 0:
            return math.inf
        return (wins / visits) + c * math.sqrt(math.log(self.parent.visits) / visits)

    def best_child(self, c: float = C_PUCT) -> "MCTSNode":
        """Return child with highest UCB score."""
        return max(self.children, key=lambda child: child.ucb_score(c))

    def expand(self) -> "MCTSNode":
        """Same as mcts.py MCTSNode.expand()."""
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (copy from mcts.py)
        # ---------------------------------------------------------------------------
        move = self.untried_moves.pop()
        move = (int(move[0]), int(move[1]))
        new_board = self.board.copy()
        new_board.make_move(move[0], move[1], self.player)
        child = MCTSNode(new_board, 3 - self.player, self, move)
        self.children.append(child)
        return child

    def backpropagate(self, result: float) -> None:
        """Same as mcts.py MCTSNode.backpropagate()."""
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (copy from mcts.py)
        # ---------------------------------------------------------------------------
        self.visits += 1
        self.wins += result
        if self.parent:
            self.parent.backpropagate(1 - result)


# ===========================================================================
# PART 4 — PHASE 1: MCTS EXPLORATION
# ===========================================================================

def mcts_phase(board: Board, player: int,
               time_budget: float) -> list:
    """
    Run MCTS for `time_budget` seconds and return the top-K children
    of root sorted by visit count (descending).

    This is identical to mcts_search() main loop, but:
        - Uses `time_budget` instead of `time_limit`
        - Returns top-K children instead of the single best move

    Algorithm:
        root = MCTSNode(board.copy(), player)
        Run standard 4-phase MCTS loop until time_budget expires.
        Return sorted(root.children, by visits, descending)[:TOP_K]

    INPUT:
        board       : Board
        player      : 1 or 2
        time_budget : seconds allocated to MCTS phase
    OUTPUT:
        list of MCTSNode — top-K children by visit count
        (may be shorter than TOP_K if tree has fewer children)

    HINT: print MCTS iteration count at the end for debugging.
    """
    root  = MCTSNode(board.copy(), player)
    start = time.time()
    iterations = 0

    while time.time() - start < time_budget:
        # ---------------------------------------------------------------------------
        # YOUR CODE HERE  (~15 lines, same as mcts_search loop)
        # ---------------------------------------------------------------------------
        node = root
        while node.is_fully_expanded() and not node.is_terminal():
            node = node.best_child()

        if not node.is_terminal():
            node = node.expand()
            result = _rollout(node.board, node.player)
            node.backpropagate(result)
        else:
            result = 0.5
            node.backpropagate(result)
        iterations += 1

    print(f"[Phase 1] MCTS iterations: {iterations}")
    top_k = sorted(root.children, key=lambda c: c.visits, reverse=True)[:TOP_K]
    return top_k


# ===========================================================================
# PART 5 — PHASE 2: MINIMAX REFINEMENT  (anytime, iterative deepening)
# ===========================================================================

def _minimax(board: Board, depth: int, alpha: float, beta: float,
             is_maximizing: bool, player: int,
             last_move: Optional[Tuple[int, int]],
             start: float, time_limit: float) -> Optional[int]:
    """
    Minimax with alpha-beta + time guard — same as minimax.py _minimax().

    Returns None when time budget is exhausted.

    HINT: copy your _minimax() implementation from minimax.py here.

    INPUT:  board, depth, alpha, beta, is_maximizing, player,
            last_move, start, time_limit
    OUTPUT: int or None
    """
    # ---------------------------------------------------------------------------
    # YOUR CODE HERE  (copy from minimax.py)
    # ---------------------------------------------------------------------------
    opponent = 3 - player

    # time
    if time.time() - start >= time_limit:
        return None

    # win check
    if last_move is not None:
        last_player = player if is_maximizing else opponent
        if board.check_win(last_move[0], last_move[1], last_player):
            return WIN_SCORE if last_player == player else LOSE_SCORE

    # depth limit
    if depth == 0:
        return evaluate(board, player)

    # draw
    if board.is_full():
        return 0

    sorted_moves = get_candidate_moves(board)[:MAX_CANDIDATES]

    if is_maximizing:
        best = -math.inf
        for (r, c) in sorted_moves:
            board.make_move(r, c, player)
            score = _minimax(board, depth - 1, alpha, beta, False, player, (r, c), start, time_limit)
            board.undo_move(r, c)

            if score is None:
                return None
            best = max(best, score)
            alpha = max(alpha, best)
            if beta <= alpha:
                break

        return best

    else:
        best = math.inf
        for (r, c) in sorted_moves:
            # mirror of maximizer block above
            board.make_move(r, c, opponent)
            score = _minimax(board, depth - 1, alpha, beta, True, player, (r, c), start, time_limit)
            board.undo_move(r, c)

            if score is None:
                return None
            best = min(best, score)
            beta = min(beta, best)
            if beta <= alpha:
                break

        return best



def minimax_phase(board: Board, player: int,
                  top_k_nodes: list,
                  time_budget: float) -> Tuple[int, int]:
    """
    Refine top-K MCTS candidates with iterative-deepening minimax.

    Algorithm:
        time_per_node = time_budget / len(top_k_nodes)

        For each node in top_k_nodes:
            Run iterative deepening minimax from node.board
            with budget = time_per_node.
            Record best_score and best_depth reached.

        Return the move of the node with the highest minimax score.

    Iterative deepening per node:
        best_score = -inf
        for depth in range(1, MAX_DEPTH + 1):
            if time expired for this node: break
            score = _minimax(node.board, depth, -inf, +inf,
                             False,   ← opponent moves next (node.player)
                             player,  ← we are always MAX
                             node.move, start_for_this_node, time_per_node)
            if score is None: break   ← time ran out mid-search
            best_score = score        ← completed depth, update

    INPUT:
        board        : Board (original, used only for fallback)
        player       : 1 or 2
        top_k_nodes  : list of MCTSNode from mcts_phase()
        time_budget  : seconds allocated to minimax phase
    OUTPUT:
        Tuple[int, int] — move with highest refined minimax score

    CONSTANTS you may use:
        MAX_DEPTH = 20
    """
    MAX_DEPTH = 20

    if not top_k_nodes:
        # Fallback: no MCTS candidates, pick first legal move
        return get_candidate_moves(board)[0]

    # ---------------------------------------------------------------------------
    # YOUR CODE HERE  (~30 lines)
    # ---------------------------------------------------------------------------
    time_per_node = time_budget / len(top_k_nodes)
    best_score = -math.inf
    best_move = None
    start = time.time()
    best_overall_score = -math.inf
    best_move = top_k_nodes[0].move  # fallback

    for node in top_k_nodes:
        node_best_score = -math.inf
        start_node = time.time()
        for depth in range(1, MAX_DEPTH + 1):
            if time.time() - start_node >= time_per_node:
                break
            score = _minimax(node.board, depth, -math.inf, math.inf,
                            False, player, node.move, start_node, time_per_node)
            if score is None:
                break
            node_best_score = score

        if node_best_score > best_overall_score:
            best_overall_score = node_best_score
            best_move = node.move

    return best_move


# ===========================================================================
# PART 6 — HYBRID SEARCH  (orchestrates Phase 1 + Phase 2)
# ===========================================================================

def hybrid_search(board: Board, player: int,
                  time_limit: float = 15.0) -> Tuple[int, int]:
    """
    Hybrid MCTS + Minimax search.

    Pipeline:
        1. Pre-check immediate win or block → return instantly if found.
        2. Phase 1 — MCTS exploration    (first half of time_limit)
        3. Phase 2 — Minimax refinement  (second half of time_limit)
        4. Return best move from Phase 2.

    Time split:
        phase1_budget = time_limit * 0.5
        phase2_budget = time_limit * 0.5   (split equally among TOP_K nodes)

    INPUT:
        board      : Board
        player     : 1 or 2
        time_limit : total wall-clock budget in seconds (default 15s)
    OUTPUT:
        Tuple[int, int] — best (r, c) move
    """
    start = time.time()

    # Pre-check: immediate win or block
    candidates = get_candidate_moves(board)
    for move in candidates:
        board.make_move(move[0], move[1], player)
        if board.check_win(move[0], move[1], player):
            board.undo_move(move[0], move[1])
            return move
        board.undo_move(move[0], move[1])

    opponent = 3 - player
    for move in candidates:
        board.make_move(move[0], move[1], opponent)
        if board.check_win(move[0], move[1], opponent):
            board.undo_move(move[0], move[1])
            return move
        board.undo_move(move[0], move[1])

    # ---------------------------------------------------------------------------
    # YOUR CODE HERE  (~8 lines)
    # Split time_limit into phase1_budget and phase2_budget.
    # Call mcts_phase() then minimax_phase() and return result.
    # ---------------------------------------------------------------------------
    phase1_budget = time_limit * 0.5
    phase2_budget = time_limit * 0.5
    top_k = mcts_phase(board, player, phase1_budget)
    move = minimax_phase(board, player, top_k, phase2_budget)
    return move


# ===========================================================================
# TESTS
# ===========================================================================
if __name__ == "__main__":
    board = Board(15)

    # ------------------------------------------------------------------
    # 1. evaluate — empty board
    # ------------------------------------------------------------------
    assert evaluate(board, 1) == 0
    assert evaluate(board, 2) == 0
    print("PASS: evaluate empty board")

    # ------------------------------------------------------------------
    # 2. evaluate — symmetry
    # ------------------------------------------------------------------
    board.make_move(0, 0, 1); board.make_move(1, 0, 1)
    board.make_move(2, 0, 2); board.make_move(3, 0, 2)
    assert evaluate(board, 1) == -evaluate(board, 2)
    board.grid[:] = 0
    print("PASS: evaluate symmetry")

    # ------------------------------------------------------------------
    # 3. mcts_phase — returns at most TOP_K nodes
    # ------------------------------------------------------------------
    board.make_move(7, 7, 1)
    top_k = mcts_phase(board, player=2, time_budget=2.0)
    assert len(top_k) <= TOP_K, f"mcts_phase must return <= {TOP_K} nodes"
    assert all(n.move is not None for n in top_k)
    board.grid[:] = 0
    print(f"PASS: mcts_phase returned {len(top_k)} candidates")

    # ------------------------------------------------------------------
    # 4. minimax_phase — returns a valid move
    # ------------------------------------------------------------------
    board.make_move(7, 7, 1)
    top_k = mcts_phase(board, player=2, time_budget=2.0)
    move  = minimax_phase(board, player=2, top_k_nodes=top_k, time_budget=3.0)
    assert move is not None
    assert board.is_valid(move[0], move[1])
    board.grid[:] = 0
    print(f"PASS: minimax_phase returned valid move {move}")

    # ------------------------------------------------------------------
    # 5. hybrid_search — take winning move immediately
    # ------------------------------------------------------------------
    for col in range(4):
        board.make_move(0, col, 1)
    move = hybrid_search(board, player=1, time_limit=15.0)
    assert move == (0, 4), f"Hybrid should complete 5-in-row, got {move}"
    board.grid[:] = 0
    print("PASS: hybrid_search takes win")

    # ------------------------------------------------------------------
    # 6. hybrid_search — block opponent's open 4
    # ------------------------------------------------------------------
    for col in range(4):
        board.make_move(0, col, 2)
    move = hybrid_search(board, player=1, time_limit=15.0)
    assert move == (0, 4), f"Hybrid should block row 0, got {move}"
    board.grid[:] = 0
    print("PASS: hybrid_search blocks opponent 4")

    # ------------------------------------------------------------------
    # 7. hybrid_search — returns within time limit
    # ------------------------------------------------------------------
    random.seed(42)
    for _ in range(10):
        r, c = random.randint(5, 9), random.randint(5, 9)
        if board.grid[r, c] == 0:
            board.make_move(r, c, random.choice([1, 2]))
    t0      = time.time()
    move    = hybrid_search(board, player=1, time_limit=15.0)
    elapsed = time.time() - t0
    assert move is not None,   "must always return a move"
    assert elapsed <= 16.0,    f"exceeded time limit: {elapsed:.1f}s"
    board.grid[:] = 0
    print(f"PASS: hybrid_search returned in {elapsed:.2f}s")

    print("\n=== All tests passed! ===")