# -*- coding: utf-8 -*-
"""game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bjPv1DmQZoxlWhiLVkMaqogGWSTSvAJD
"""

import numpy as np
from typing import List, Tuple, Optional

class Board:
    def __init__(self, size: int = 15):
        """Initialize empty board."""

        self.grid = np.zeros((size, size), dtype=int)
        self.size = size

    def copy(self):
        new = Board(self.size)
        new.grid = self.grid.copy()  
        return new

    def is_valid(self, row: int, col: int) -> bool:
        """Check if a cell is within bounds and empty."""

        if row < 0 or row >= self.size or col < 0 or col >= self.size: # False if a cell if out of bound.
            return False

        if self.grid[row, col] != 0: # False if a cell is occupied.
            return False

        return True # True if cell is valid.

    def make_move(self, row: int, col: int, player: int) -> bool:
        """Place a piece on the board."""

        if self.is_valid(row, col) == False: # False if invalid move
            return False

        self.grid[row, col] = player
        return True # True if move successful

    def undo_move(self, row: int, col: int) -> None:
        """Remove a piece from the board (used by minimax)."""
        self.grid[row, col] = 0

    def is_full(self) -> bool:
        """Check if board has no empty cells."""
        if np.all(self.grid != 0):
            return True
        return False

    def get_empty_cells(self) -> List[Tuple[int, int]]:
        """Return list of all empty cell coordinates."""
        return [tuple(int(x) for x in cell) for cell in np.argwhere(self.grid == 0)]

    def check_win(self, row: int, col: int, player: int) -> bool:
        """
        Check if the last move at (row, col) caused player to win.
        Win = 5 consecutive pieces in any direction.
        """
        AXES = [
            [(0, 1),  (0, -1)],
            [(1, 0),  (-1, 0)],
            [(1, 1),  (-1, -1)],
            [(1, -1), (-1, 1)],
        ]

        for axis in AXES:
            count = 1
            for (dr, dc) in axis:
                r, c = row + dr, col + dc

                # Walk in this direction while same player
                while 0 <= r < self.size and 0 <= c < self.size and self.grid[r, c] == player:
                    count += 1
                    r, c = r + dr, c + dc

            if count >= 5: # Check if 5 in a row
                return True

        return False


# ==================== TESTS ====================
if __name__ == "__main__":
    board = Board(15)

    # Test __init__
    assert board.size == 15
    assert board.grid.shape == (15, 15)
    assert board.grid.sum() == 0
    print("PASS: __init__")

    # Test is_valid
    assert board.is_valid(0, 0) == True
    assert board.is_valid(14, 14) == True
    assert board.is_valid(15, 0) == False
    assert board.is_valid(0, -1) == False
    print("PASS: is_valid bounds")

    # Test make_move
    assert board.make_move(7, 7, 1) == True
    assert board.grid[7, 7] == 1
    assert board.is_valid(7, 7) == False
    assert board.make_move(7, 7, 2) == False
    print("PASS: make_move + is_valid occupied")

    # Test undo_move
    board.undo_move(7, 7)
    assert board.grid[7, 7] == 0
    assert board.is_valid(7, 7) == True
    print("PASS: undo_move")

    # Test is_full
    assert board.is_full() == False
    board.grid[:] = 1
    assert board.is_full() == True
    board.grid[:] = 0
    print("PASS: is_full")

    # Test get_empty_cells
    cells = board.get_empty_cells()
    assert len(cells) == 225
    board.make_move(0, 0, 1)
    cells = board.get_empty_cells()
    assert len(cells) == 224
    assert (0, 0) not in cells
    board.undo_move(0, 0)
    cells = board.get_empty_cells()
    assert isinstance(cells[0], tuple), "Should return list of tuples"
    assert isinstance(cells[0][0], int), "Should be Python int, not numpy int64"
    print("PASS: get_empty_cells")

    # Test check_win horizontal
    for col in range(5):
        board.make_move(0, col, 1)
    assert board.check_win(0, 4, 1) == True
    assert board.check_win(0, 4, 2) == False
    board.grid[:] = 0
    print("PASS: check_win horizontal")

    # Test check_win vertical
    for row in range(5):
        board.make_move(row, 0, 2)
    assert board.check_win(4, 0, 2) == True
    board.grid[:] = 0
    print("PASS: check_win vertical")

    # Test check_win diagonal
    for i in range(5):
        board.make_move(i, i, 1)
    assert board.check_win(4, 4, 1) == True
    board.grid[:] = 0
    print("PASS: check_win diagonal")

    # Test check_win anti-diagonal
    for i in range(5):
        board.make_move(i, 4 - i, 1)
    assert board.check_win(4, 0, 1) == True
    board.grid[:] = 0
    print("PASS: check_win anti-diagonal")

    # Test check_win: 4 in a row should NOT win
    for col in range(4):
        board.make_move(0, col, 1)
    assert board.check_win(0, 3, 1) == False
    board.grid[:] = 0
    print("PASS: check_win 4 in a row not win")

    # Test check_win: 6 in a row SHOULD win (no restriction in basic gomoku)
    for col in range(6):
        board.make_move(0, col, 1)
    assert board.check_win(0, 5, 1) == True
    board.grid[:] = 0
    print("PASS: check_win 6 in a row")

    print("\nAll tests passed!")